file type, max and min document fields added and keys are refactored
avi-soft/am-apis pull request #236
Opened 2024-11-14 07:25 UTC by simran2519

file type, max and min document fields added and keys are refactored

2024-11-14 07:51 UTC, raman-kumar-avisoft requested changes

2024-11-14 07:51 UTC, raman-kumar-avisoft commented on api/src/main/java/com/community/api/endpoint/avisoft/controller/Customer/CustomerEndpoint.java
>  import java.util.*;
dont import all classes use spefic classes only

2024-11-14 07:51 UTC, raman-kumar-avisoft commented on api/src/main/java/com/community/api/endpoint/avisoft/controller/Customer/CustomerEndpoint.java
>  import com.community.api.services.*;
don't use astric while importing classes

2024-11-14 07:51 UTC, raman-kumar-avisoft commented on api/src/main/java/com/community/api/entity/FileType.java
> +import javax.persistence.*;
dont;s use astric while importing classes

2024-11-14 07:51 UTC, raman-kumar-avisoft commented on api/src/main/java/com/community/api/services/DocumentStorageService.java
use multiline comments and while generating a PR try to remove commented code (can also add commented code as well but only neccesary).

2024-11-14 07:51 UTC, raman-kumar-avisoft commented on api/src/main/java/com/community/api/utils/DocumentType.java
>  import javax.persistence.*;
Don't use astrics while importing

2024-11-14 07:51 UTC, raman-kumar-avisoft commented on api/src/main/java/com/community/api/utils/DocumentType.java
> +
use multiline comments and try to remove the commented code

2024-11-14 07:51 UTC, raman-kumar-avisoft commented on core/src/main/resources/runtime-properties/common-shared.properties
> -#database.url=jdbc:postgresql://localhost:5432/broadleaf
don' remove those line from the code they are for developer ease as we don't have to write those lines again if we want to use local db .

2024-11-18 06:37 UTC, kshtjvats approved these changes

2024-11-18 06:38 UTC, merged